<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="CODE_TempleOfDoom_DownloadableContent">
      <HintPath>..\..\..\OneDrive\Documenten\School\Jaar 3\Code\CODE_TempleOfDoom_DownloadableContent\CODE_TempleOfDoom_DownloadableContent.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="resources\TempleOfDoom_Extended_B_2122.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
